-- | Placeholder PureScript module that exists only so spago / purs-
-- | backend-erl pair the sibling `Handler.erl` foreign file as
-- | `tidal_webSocket_handler@foreign` and copy it into output-erl
-- | for the Makefile's `find … -exec erlc` pass.
-- |
-- | Cowboy's dispatch (in `Tidal.WebSocket.Server`) refers to that
-- | module name directly via `NativeModuleName`. Without this empty
-- | PS file the foreign .erl wouldn't end up in ebin/ and the
-- | WebSocket handler would never start.
-- |
-- | All the actual WS verb parsing + dispatch lives in `Handler.erl`.
module Tidal.WebSocket.Handler where
