#!/usr/bin/env node
// Phase 2 orchestrator: arm a cue on a tvoice via the typeful path.
//
// Usage: node scripts/arm-cue.mjs <tvoice> <cue-name>
//   e.g. node scripts/arm-cue.mjs bass1 bass1A
//        node scripts/arm-cue.mjs bass1 bass1B
//
// Synthesises a bridge module Tidal.Generated.M<tvoice> that extracts
// the body from <cue-name>'s typeful Cue value, builds it via purs +
// `purs-backend-erl --filter` (scoped emit; see purerl-leaf-edit-
// benchmark findings), erlc's the resulting .erl, then sends
// `play-armed <tvoice> M<tvoice>` over the WS.  The handler's
// code:load_file step forces the BEAM to pick up the freshly-built
// .beam; the voice gen_server's pattern swaps on the next cycle.
//
// Glob caching: the script needs the full purs source-file glob to
// invoke purs compile directly (bypassing spago's overhead). On first
// run it dumps the glob via `spago build --verbose` and caches it to
// .arm-cue/purs-glob.txt. Subsequent runs read the cache, which is
// invalidated by `rm .arm-cue/purs-glob.txt` or when spago.yaml is
// newer than the cache.
import {
  writeFileSync,
  readFileSync,
  existsSync,
  statSync,
  mkdirSync,
  rmSync,
} from 'node:fs'
import { execSync, spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..')

// ---------------------------------------------------------------------------
const [, , tvoice, cueName] = process.argv
if (!tvoice || !cueName) {
  console.error('Usage: node scripts/arm-cue.mjs <tvoice> <cue-name>')
  console.error('  e.g. node scripts/arm-cue.mjs bass1 bass1A')
  process.exit(1)
}

const sessionModule = 'Calypso.Generated.Session'
// PS module convention: leading M is the per-cell-compile prefix; the
// rest is all-lowercase. purs-backend-erl lowercases module names when
// emitting the .erl FILE name but preserves source caps in the
// -module() declaration — so any uppercase char causes a
// module-name-vs-filename mismatch at erlc time. Keep the tail all-lc.
const tvoiceTail = tvoice.toLowerCase().replace(/[^a-z0-9]/g, '')
const bridgeModule = `Tidal.Generated.M${tvoiceTail}`
const bridgePsPath = join(
  repoRoot,
  'src',
  'Tidal',
  'Generated',
  `M${tvoiceTail}.purs`
)
const bridgeErlBase = `tidal_generated_m${tvoiceTail}@ps`
const bridgeErlPath = join(
  repoRoot,
  'output-erl',
  bridgeModule,
  `${bridgeErlBase}.erl`
)
const buildTxt = join(repoRoot, 'output-erl', 'build.txt')
const beamOut = join(repoRoot, 'ebin')
const cacheDir = join(repoRoot, '.arm-cue')
const globCachePath = join(cacheDir, 'purs-glob.txt')

// ---------------------------------------------------------------------------
// 1. Write the bridge module
const bridgeSrc = `-- | Generated by scripts/arm-cue.mjs at ${new Date().toISOString()}
-- | tvoice: ${tvoice}  armed cue: ${cueName}
module ${bridgeModule} where

import Tidal.Pattern.Types (Pattern)
import Calypso.Prelude (Cue(..))
import ${sessionModule} (${cueName})

pattern :: Pattern String
pattern = case ${cueName} of
  Cue r -> r.body
`
writeFileSync(bridgePsPath, bridgeSrc)
console.log(`[arm-cue] wrote ${bridgePsPath}`)

// ---------------------------------------------------------------------------
// 2. Get the purs glob (cached after first run)
mkdirSync(cacheDir, { recursive: true })

function deriveGlob() {
  console.log('[arm-cue] deriving purs glob via `spago build --verbose`…')
  const r = spawnSync('spago', ['build', '--verbose'], {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf-8',
  })
  // The verbose output includes a `purs compile --codegen corefn,docs
  // --json-errors <huge glob>` line we want to extract.
  const lines = (r.stdout + r.stderr).split('\n')
  for (const line of lines) {
    const i = line.indexOf('purs compile ')
    if (i >= 0) return line.slice(i + 'purs compile '.length).trim()
  }
  throw new Error('could not extract purs glob from spago --verbose output')
}

let pursGlob
const spagoYaml = join(repoRoot, 'spago.yaml')
const cacheStale =
  !existsSync(globCachePath) ||
  statSync(globCachePath).mtimeMs < statSync(spagoYaml).mtimeMs
if (cacheStale) {
  pursGlob = deriveGlob()
  writeFileSync(globCachePath, pursGlob)
  console.log(`[arm-cue] cached purs glob to ${globCachePath}`)
} else {
  pursGlob = readFileSync(globCachePath, 'utf-8').trim()
}

// ---------------------------------------------------------------------------
// 3. Run purs compile directly to refresh corefn (much faster than spago)
const t0 = Date.now()
console.log('[arm-cue] purs compile (incremental)…')
const tPurs0 = Date.now()
// purs accepts the glob as a shell expansion; bash -O globstar makes
// '**/*.purs' expand to all matching files (default /bin/sh / bash
// have globstar disabled).
const pursResult = spawnSync(
  'bash',
  ['-O', 'globstar', '-c', `purs compile ${pursGlob}`],
  {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf-8',
  }
)
if (pursResult.status !== 0) {
  console.error('[arm-cue] purs compile FAILED:')
  console.error(pursResult.stdout)
  console.error(pursResult.stderr)
  process.exit(2)
}
const tPurs = Date.now() - tPurs0
console.log(`[arm-cue] purs compile done in ${tPurs}ms`)

// ---------------------------------------------------------------------------
// 4. Invalidate backend-erl cache; run scoped emit via --filter
console.log(`[arm-cue] backend-erl --filter ${bridgeModule}`)
const tBe0 = Date.now()
try {
  rmSync(buildTxt)
} catch (_) {
  /* may not exist */
}
const beResult = spawnSync(
  'node_modules/.bin/purs-backend-erl',
  ['--filter', bridgeModule],
  {
    cwd: repoRoot,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf-8',
  }
)
if (beResult.status !== 0) {
  console.error('[arm-cue] backend-erl FAILED:')
  console.error(beResult.stdout)
  console.error(beResult.stderr)
  process.exit(3)
}
const tBe = Date.now() - tBe0
console.log(`[arm-cue] backend-erl done in ${tBe}ms`)

// ---------------------------------------------------------------------------
// 5. erlc the bridge .erl → ebin/<bridgeErlBase>.beam
console.log(`[arm-cue] erlc ${bridgeErlPath}`)
try {
  statSync(bridgeErlPath)
} catch (_) {
  console.error(`[arm-cue] bridge .erl not found after build: ${bridgeErlPath}`)
  process.exit(4)
}
const tErlc0 = Date.now()
execSync(
  `erlc -disable-feature maybe_expr -o ${beamOut} ${bridgeErlPath}`,
  { cwd: repoRoot }
)
const tErlc = Date.now() - tErlc0
console.log(`[arm-cue] erlc done in ${tErlc}ms`)

// ---------------------------------------------------------------------------
// 6. Send play-armed over WS.  Uses Node 22's built-in WebSocket.
const tWs0 = Date.now()
const ws = new WebSocket('ws://localhost:3012/ws')

const armWireModule = `M${tvoiceTail}`
const cmds = [
  `midi-device iac "IAC Driver Tidal"`,
  `bind ${tvoice} midi-note iac 1 36 100 50`,
  `play-armed ${tvoice} ${armWireModule}`,
]

await new Promise((resolve, reject) => {
  const replies = []

  ws.addEventListener('open', () => {
    for (const cmd of cmds) {
      ws.send(cmd)
      console.log(`[arm-cue] → ${cmd}`)
    }
  })

  ws.addEventListener('message', (evt) => {
    const text = typeof evt.data === 'string' ? evt.data : String(evt.data)
    replies.push(text)
    console.log(`[arm-cue] ← ${text}`)
    if (replies.length >= cmds.length) {
      ws.close()
      resolve()
    }
  })

  ws.addEventListener('error', (e) => {
    console.error('[arm-cue] WS error:', e)
    reject(e)
  })

  ws.addEventListener('close', () => {
    if (replies.length < cmds.length) {
      console.warn(
        `[arm-cue] WS closed after ${replies.length}/${cmds.length} replies`
      )
    }
    resolve()
  })

  setTimeout(() => {
    if (replies.length < cmds.length) {
      console.error('[arm-cue] WS timeout waiting for replies')
      ws.close()
      reject(new Error('timeout'))
    }
  }, 10000)
})

const tWs = Date.now() - tWs0
const tTotal = Date.now() - t0
console.log(
  `[arm-cue] DONE  total=${tTotal}ms  ` +
    `purs=${tPurs}ms  be=${tBe}ms  erlc=${tErlc}ms  ws=${tWs}ms`
)
