#!/usr/bin/env node
// Phase 2 orchestrator: arm a cue on a tvoice via the typeful path.
//
// Usage: node scripts/arm-cue.mjs <tvoice> <cue-name>
//   e.g. node scripts/arm-cue.mjs bass1 bass1A
//        node scripts/arm-cue.mjs bass1 bass1B
//
// Synthesises a bridge module Tidal.Generated.M<tvoice> that extracts
// the body from <cue-name>'s typeful Cue value, builds it via
// spago/purs-backend-erl, erlc's the resulting .erl, then sends
// `play-armed <tvoice> M<tvoice>` over the WS.  The handler's
// code:load_file step forces the BEAM to pick up the freshly-built
// .beam; the voice gen_server's pattern swaps on the next cycle.
//
// Demonstrates cue hot-switching via the typeful path with no further
// changes to purerl-tidal beyond the play-armed handler's load_file
// call.
import { writeFileSync, statSync } from 'node:fs'
import { execSync, spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(__dirname, '..')

// ---------------------------------------------------------------------------
const [, , tvoice, cueName] = process.argv
if (!tvoice || !cueName) {
  console.error('Usage: node scripts/arm-cue.mjs <tvoice> <cue-name>')
  console.error('  e.g. node scripts/arm-cue.mjs bass1 bass1A')
  process.exit(1)
}

const sessionModule = 'Calypso.Generated.Session'
// PS module convention: leading M is the per-cell-compile prefix; the
// rest is all-lowercase. purs-backend-erl lowercases module names when
// emitting the .erl FILE name but preserves source caps in the
// -module() declaration — so any uppercase char causes a
// module-name-vs-filename mismatch at erlc time. Keep the tail all-lc.
const tvoiceTail = tvoice.toLowerCase().replace(/[^a-z0-9]/g, '')
const bridgeModule = `Tidal.Generated.M${tvoiceTail}`
const bridgePsPath = join(
  repoRoot,
  'src',
  'Tidal',
  'Generated',
  `M${tvoiceTail}.purs`
)
// The Erlang atom that play-armed will reach for, lowercased
const bridgeErlBase = `tidal_generated_m${tvoiceTail}@ps`
const bridgeErlPath = join(
  repoRoot,
  'output-erl',
  bridgeModule,
  `${bridgeErlBase}.erl`
)
const beamOut = join(repoRoot, 'ebin')

// ---------------------------------------------------------------------------
// 1. Write the bridge module
const bridgeSrc = `-- | Generated by scripts/arm-cue.mjs at ${new Date().toISOString()}
-- | tvoice: ${tvoice}  armed cue: ${cueName}
module ${bridgeModule} where

import Tidal.Pattern.Types (Pattern)
import Calypso.Prelude (Cue(..))
import ${sessionModule} (${cueName})

pattern :: Pattern String
pattern = case ${cueName} of
  Cue r -> r.body
`
writeFileSync(bridgePsPath, bridgeSrc)
console.log(`[arm-cue] wrote ${bridgePsPath}`)

// ---------------------------------------------------------------------------
// 2. Build via spago (full path for now; --filter scoping comes later)
const t0 = Date.now()
console.log('[arm-cue] spago build…')
const build = spawnSync('spago', ['build'], {
  cwd: repoRoot,
  stdio: ['ignore', 'pipe', 'pipe'],
  encoding: 'utf-8',
})
if (build.status !== 0) {
  console.error('[arm-cue] spago build FAILED:')
  console.error(build.stdout)
  console.error(build.stderr)
  process.exit(2)
}
const tBuild = Date.now() - t0
console.log(`[arm-cue] spago build done in ${tBuild}ms`)

// ---------------------------------------------------------------------------
// 3. erlc the bridge .erl → ebin/<bridgeErlBase>.beam
console.log(`[arm-cue] erlc ${bridgeErlPath}`)
try {
  statSync(bridgeErlPath)
} catch (_) {
  console.error(`[arm-cue] bridge .erl not found after build: ${bridgeErlPath}`)
  process.exit(3)
}
const tErlc0 = Date.now()
execSync(
  `erlc -disable-feature maybe_expr -o ${beamOut} ${bridgeErlPath}`,
  { cwd: repoRoot }
)
const tErlc = Date.now() - tErlc0
console.log(`[arm-cue] erlc done in ${tErlc}ms`)

// ---------------------------------------------------------------------------
// 4. Send play-armed over WS.  Uses Node 22's built-in WebSocket.
const tWs0 = Date.now()
const ws = new WebSocket('ws://localhost:3012/ws')

const armWireModule = `M${tvoiceTail}`  // play-armed lowercases on its end
const cmds = [
  `midi-device iac "IAC Driver Tidal"`,         // idempotent device register
  `bind ${tvoice} midi-note iac 1 36 100 50`,   // idempotent re-bind
  `play-armed ${tvoice} ${armWireModule}`,
]

await new Promise((resolve, reject) => {
  const replies = []
  let sent = 0

  ws.addEventListener('open', () => {
    // wscat-style leading delay isn't needed for built-in WebSocket
    // because we send only after `open` fires
    for (const cmd of cmds) {
      ws.send(cmd)
      console.log(`[arm-cue] → ${cmd}`)
      sent++
    }
  })

  ws.addEventListener('message', (evt) => {
    const text = typeof evt.data === 'string' ? evt.data : String(evt.data)
    replies.push(text)
    console.log(`[arm-cue] ← ${text}`)
    if (replies.length >= cmds.length) {
      ws.close()
      resolve()
    }
  })

  ws.addEventListener('error', (e) => {
    console.error('[arm-cue] WS error:', e)
    reject(e)
  })

  ws.addEventListener('close', () => {
    if (replies.length < cmds.length) {
      console.warn(
        `[arm-cue] WS closed after ${replies.length}/${cmds.length} replies`
      )
    }
    resolve()
  })

  setTimeout(() => {
    if (replies.length < cmds.length) {
      console.error('[arm-cue] WS timeout waiting for replies')
      ws.close()
      reject(new Error('timeout'))
    }
  }, 10000)
})

const tWs = Date.now() - tWs0
const tTotal = Date.now() - t0
console.log(
  `[arm-cue] DONE  total=${tTotal}ms  ` +
    `build=${tBuild}ms  erlc=${tErlc}ms  ws=${tWs}ms`
)
